# 변경 불필요
languageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
baseURL = "https://ksmin23.github.io/analytics-on-aws/"
#publishDir = "docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = false
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "aws"
disableInlineCopyToClipBoard = false
# 변경 필요
author = "Sungmin Kim"

# 변경 필요
title = "Analytics on AWS"
#googleAnalytics = ""

[[menu.shortcuts]] 
name = "<i class='fab fa-aws'></i> AWS Homepage"
url = "https://aws.amazon.com/"
weight = 1000

[[menu.shortcuts]]
name = "<i class='fas fa-blog'></i> AWS Blog"
url = "https://aws.amazon.com/blogs/aws/"
weight = 1020

[[menu.shortcuts]]
name = "<i class='fab fa-facebook-square'></i> Facebook"
url = "https://www.facebook.com/groups/awskrug/"
weight = 1030

[Languages]
[Languages.ko]
  weight = 1
  languageName = "한국어"

[Languages.en]
  weight = 2
  languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL="s3://hugo-workshop-apne2/dev/?region=ap-northeast-2"
